In [5]:
import os
import pandas as pd
import numpy as np

# py-slippi
from slippi import Game

In [6]:
PATH='dataset/demo/inference'
SEQ_LEN=180

In [7]:
id_to_player = {0: '2saint',
 1: 'aklo',
 2: 'amsa',
 3: 'axe',
 4: 'cody',
 5: 'cpu',
 6: 'cynthia',
 7: 'hbox',
 8: 'kodorin',
 9: 'logan',
 10: 'mang0',
 11: 'moky',
 12: 'n0ne',
 13: 'plup',
 14: 'sfat',
 15: 'wizzrobe',
 16: 'yingling',
 17: 'zain'}

## Load the game

In [8]:
file = os.path.join(PATH, os.listdir(PATH)[0])
game = Game(file)
game

Game(
    end=End(
        lras_initiator=0,
        method=7:NO_CONTEST),
    frames=[...](1592),
    metadata=Metadata(
        console_name=None,
        date=2024-05-01 21:31:26+00:00,
        duration=1592,
        platform='dolphin':DOLPHIN,
        players=(
            Player(
                characters={9:PEACH: 1592},
                netplay=None),
            None,
            None,
            Player(
                characters={23:PICHU: 1592},
                netplay=None))),
    start=Start(
        is_frozen_ps=False,
        is_pal=False,
        is_teams=False,
        players=(
            Player(
                character=12:PEACH,
                costume=0,
                stocks=4,
                tag=,
                team=None,
                type=0:HUMAN,
                ucf=UCF(
                    dash_back=1:UCF,
                    shield_drop=1:UCF)),
            None,
            None,
            Player(
                character=24:PICHU,
                costume=0,
                stocks=4,
                tag=,
                team=None,
                type=1:CPU,
                ucf=UCF(
                    dash_back=1:UCF,
                    shield_drop=1:UCF))),
        random_seed=3416337533,
        slippi=Slippi(
            version=3.16.0),
        stage=32:FINAL_DESTINATION))

In [9]:
game.frames[0]

Frame(
    end=End(
    ),
    index=-123,
    items=(),
    ports=(
        Port(
            follower=None,
            leader=Data(
                post=Post(
                    airborne=True,
                    character=9:PEACH,
                    combo_count=0,
                    damage=0.00,
                    direction=1:RIGHT,
                    flags=0b100000000000000000000000000000000000000:DEAD,
                    ground=None,
                    hit_stun=0.00,
                    jumps=1,
                    l_cancel=None,
                    last_attack_landed=None,
                    last_hit_by=None,
                    position=(-60.00, 10.00),
                    shield=60.00,
                    state=322:ENTRY,
                    state_age=-1.00,
                    stocks=4),
                pre=Pre(
                    buttons=Buttons(
                        logical=0b0:NONE,
                        physical=0b0:NONE),
                    cstick=(0.00, 0.00),
                    damage=0.00,
                    direction=1:RIGHT,
                    joystick=(0.00, 0.00),
                    position=(-60.00, 10.00),
                    random_seed=1961570990,
                    raw_analog_x=0,
                    state=322:ENTRY,
                    triggers=Triggers(
                        logical=0.00,
                        physical=Physical(
                            l=0.00,
                            r=0.00))))),
        None,
        None,
        Port(
            follower=None,
            leader=Data(
                post=Post(
                    airborne=True,
                    character=23:PICHU,
                    combo_count=0,
                    damage=0.00,
                    direction=-1:LEFT,
                    flags=0b100000000000000000000000000000000000000:DEAD,
                    ground=None,
                    hit_stun=0.00,
                    jumps=1,
                    l_cancel=None,
                    last_attack_landed=None,
                    last_hit_by=None,
                    position=(60.00, 10.00),
                    shield=60.00,
                    state=322:ENTRY,
                    state_age=-1.00,
                    stocks=4),
                pre=Pre(
                    buttons=Buttons(
                        logical=0b0:NONE,
                        physical=0b0:NONE),
                    cstick=(0.00, 0.00),
                    damage=0.00,
                    direction=-1:LEFT,
                    joystick=(0.00, 0.00),
                    position=(60.00, 10.00),
                    random_seed=1961570990,
                    raw_analog_x=0,
                    state=322:ENTRY,
                    triggers=Triggers(
                        logical=0.00,
                        physical=Physical(
                            l=0.00,
                            r=0.00)))))),
    start=Start(
        random_seed=2639611796))

## Get the inputs from the game

In [10]:
# get the port indices used by the players
def getPorts(game):
    ports = []
    for i in range(0, len(game.start.players)):
        if game.start.players[i] is not None:
            ports.append(i)

    return ports

# get the characters for each player, just for fun
def getCharacters(game):
    characters = []
    for player in game.start.players:
        if player is not None:
            characters.append(player.character)
    
    return characters

In [11]:
getCharacters(game)

[12:PEACH, 24:PICHU]

In [13]:
START_FRAME = 64 # game starts on frame 64
COLS = ['joy_x', 'joy_y', 'cstick_x', 'cstick_y', 'z', 'r_dig', 'l_dig', 'a', 'b', 'x', 'y']
BUTTONS = ['Z', 'R', 'L', 'A', 'B', 'X', 'Y'] # names of the buttons in py-slippi

def getFrameInputs(player):
    # analog stick / c stick
    analog = [player.joystick.x, player.joystick.y, player.cstick.x, player.cstick.y]

    # buttons
    pressed_buttons = []
    # get the names of the buttons currently being pressed
    logical_pressed_names = map(lambda x: x.name, player.buttons.physical.pressed())

    for b in BUTTONS:

        if b in logical_pressed_names:
            pressed_buttons.append(1)
        else:
            pressed_buttons.append(0)

    return analog + pressed_buttons 

def getGameInputs(game):
    p1_inputs = pd.DataFrame(columns=COLS)
    p2_inputs = pd.DataFrame(columns=COLS)

    # get the controller port #s of the players
    p1_port, p2_port = getPorts(game)

    for i in range(START_FRAME, len(game.frames)):
        p1 = game.frames[i].ports[p1_port].leader.pre 
        p1_inputs.loc[len(p1_inputs.index)] = getFrameInputs(p1)

        p2 = game.frames[i].ports[p2_port].leader.pre
        p2_inputs.loc[len(p2_inputs.index)] = getFrameInputs(p2)

    return p1_inputs, p2_inputs

In [14]:
p1_inputs, _ = getGameInputs(game)
p1_inputs.head(10)

   joy_x  joy_y  cstick_x  cstick_y    z  r_dig  l_dig    a    b    x    y
0    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
1    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
2    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
3    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
4    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
5    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
6    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
7    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
8    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0
9    0.0    0.0       0.0       0.0  0.0    0.0    0.0  0.0  0.0  0.0  0.0

In [15]:
p1_inputs.shape

(1528, 11)

## Compute the displacement vectors

In [16]:
def nextDisplacement(df, index):
    velocities = [] # stores both x and y displacement
    for col in df.columns:
        velocities.append(df.at[index+1, col] - df.at[index, col])

    return velocities

def gameDisplacements(game):
    
    ds = []
    prev_frame = 0
    for i in range(game.shape[0] - 1):
        # get next displacement
        d = nextDisplacement(game, i)

        if not d == [0, 0]: # only include frames that have some velocity
            # get elapsed
            elapsed = i - prev_frame
            prev_frame = i

            if elapsed > 60: # arbitrarily set all values > 60 to 0
                elapsed = 0

            ds.append((d[0], d[1], elapsed))
    
    return pd.DataFrame(ds, columns=['joy_x', 'joy_y', 'elapsed'])

In [17]:
displacements = gameDisplacements(p1_inputs[['joy_x', 'joy_y']])

In [18]:
displacements.head(10)

    joy_x   joy_y  elapsed
0  0.9250  0.0000       31
1  0.0500  0.0000        1
2 -0.0125  0.0000        4
3 -0.0250 -0.3125        1
4 -0.0500 -0.1250        1
5 -0.0750 -0.1375        1
6 -0.0750 -0.0875        1
7 -0.0250 -0.0250        1
8 -0.0250 -0.0250        1
9 -0.0125 -0.0125        1

In [19]:
displacements.shape

(336, 3)

## Normalize elapsed values

In [20]:
max = 60

normed = displacements.copy()
normed['elapsed'] = normed['elapsed'].map(lambda x : x / max)

In [22]:
normed.head(10)

    joy_x   joy_y   elapsed
0  0.9250  0.0000  0.516667
1  0.0500  0.0000  0.016667
2 -0.0125  0.0000  0.066667
3 -0.0250 -0.3125  0.016667
4 -0.0500 -0.1250  0.016667
5 -0.0750 -0.1375  0.016667
6 -0.0750 -0.0875  0.016667
7 -0.0250 -0.0250  0.016667
8 -0.0250 -0.0250  0.016667
9 -0.0125 -0.0125  0.016667

## Process into sequences

In [25]:
def seqs_from_df(df, seq_len=SEQ_LEN):
    """
    Arrange a dataframe of inputs into sequences of inputs of length seq_len.
    """
    seqs = []

    for i in range(0, df.shape[0] - seq_len, int(seq_len*0.25)):
        seq_x = df.loc[i:i+seq_len-1]
        seqs.append(np.array(seq_x, dtype=np.float32))
        
    return seqs

In [26]:
sequences = seqs_from_df(normed)

print(f'{len(sequences)=}')
sequences[0][0:10]

len(sequences)=4

array([[ 0.925     ,  0.        ,  0.51666665],
       [ 0.05000001,  0.        ,  0.01666667],
       [-0.01250005,  0.        ,  0.06666667],
       [-0.02499998, -0.3125    ,  0.01666667],
       [-0.05000001, -0.125     ,  0.01666667],
       [-0.07499999, -0.13749999,  0.01666667],
       [-0.07499999, -0.08750004,  0.01666667],
       [-0.02500004, -0.02499998,  0.01666667],
       [-0.02499998, -0.02499998,  0.01666667],
       [-0.01249999, -0.01250005,  0.01666667]], dtype=float32)

## Load the pre-trained model

In [27]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, ELU, Dropout, Dense, Concatenate, LSTM

gpus = tf.config.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      # allocated memory as needed, rather than 100% of it all the time
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

2024-05-01 14:39:58.859537: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-01 14:39:58.985502: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-01 14:39:58.985705: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-01 14:39:59.003173: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-01 14:39:59.046442: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-01 14:39:59.048347: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-01 14:40:00.156154: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [28]:
def createClassifier(width=3, seq_len=180):
    input_layer = Input(shape=(seq_len, width))
    conv1 = Conv1D(filters=32, kernel_size=7, strides=2, activation=ELU())(input_layer)
    conv2 = Conv1D(filters=32, kernel_size=3, strides=1, activation=ELU())(input_layer)

    catted = Concatenate(axis=1)([conv1, conv2])
    elu1 = ELU(32)(catted)
    conv3 = Conv1D(filters=32, kernel_size=2, strides=1, activation=ELU())(elu1)
    conv4 = Conv1D(filters=32, kernel_size=2, strides=1, activation=ELU())(conv3)
    drop1 = Dropout(0.2)(conv4)

    gru1 = LSTM(32, return_sequences=True)(drop1)
    gru2 = LSTM(32)(gru1)
    drop2 = Dropout(0.2)(gru2)

    output = Dense(18, activation='softmax')(drop2)

    model = Model(inputs=input_layer, outputs=output)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [29]:
model = createClassifier(3, 180)

model.load_weights('models/demo')
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 180, 3)]             0         []

 conv1d (Conv1D)             (None, 87, 32)               704       ['input_1[0][0]']

 conv1d_1 (Conv1D)           (None, 178, 32)              320       ['input_1[0][0]']

 concatenate (Concatenate)   (None, 265, 32)              0         ['conv1d[0][0]',
                                                                     'conv1d_1[0][0]']

 elu_2 (ELU)                 (None, 265, 32)              0         ['concatenate[0][0]']

 conv1d_2 (Conv1D)           (None, 264, 32)              2080      ['elu_2[0][0]']

 conv1d_3 (Conv1D)           (None, 263, 32)              2080      ['conv1d_2[0][0]']

 dropout (Dropout)           (None, 263, 32)              0         ['conv1d_3[0][0]']

 lstm (LSTM)                 (None, 263, 32)              8320      ['dropout[0][0]']

 lstm_1 (LSTM)               (None, 32)                   8320      ['lstm[0][0]']

 dropout_1 (Dropout)         (None, 32)                   0         ['lstm_1[0][0]']

 dense (Dense)               (None, 18)                   594       ['dropout_1[0][0]']

==================================================================================================
Total params: 22418 (87.57 KB)
Trainable params: 22418 (87.57 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

In [30]:
predicts = model.predict(np.array(sequences, dtype=np.float32))

hard_predicts = [np.argmax(predicts[i]) for i in range(predicts.shape[0])]

[id_to_player[hp] for hp in hard_predicts]

1/1 [==============================] - 1s 633ms/step

['cynthia', 'cynthia', 'cynthia', 'cynthia']